(function(l){var t=/^\n+/,k=/^\s+(?:at)?\s+(?:([^\(]*)\()?(.*):(\d+):(\d+)\)?$/,q=/^(([^\(]*)\([^@]+){0,1}@(.*):(\d+)(\s*)/,s=20,p=function(g,f,b,e){var h=0,a,d;
if(b){b=b.replace(t,"");
}b=b.split("\n");
d=Math.min(s,b.length);
while(h<d){a=b[h++].match(e);
if(a){var c=a.length;
g.push(a.slice(c-4,c));
}}},m=function(f,b){var d=[],e=b,c;
f=f||0;
if(!b){return[];
}c=e.stack;
if(e.arguments){(c.indexOf("\n")>=0)&&p(d,f,c,k);
}else{if(c){p(d,f,c,q);
}else{if(b){if(b.sourceURL){d.push([undefined,b.sourceURL,b.line,b.expressionBeginOffset]);
}}else{var a=arguments.callee;
e=/function\s*([-$\w]+)?\s*\(/i;
while(a&&f-->0){a=a.caller;
}while(a&&d.length<s){c=a.toString().match(e);
d.push(c?[c[1]]:[]);
a=a.caller;
}}}}return d;
},n=function(b,d,a,c){ue_err.ec++;
ue.log({m:b,f:d,l:a,s:c},"jserr");
},o=function(d){if(ue_err.ec>ue_err.mxe){return;
}var e="",a=0,b=m(0,d),c;
if(b.length>0){c=b[0];
e=c[1];
a=c[2];
}n((d?d.message:0)||"Unknown error",e,a,b);
},r=function(){if(!ue_err.erl){return;
}var b=ue_err.erl.length,a;
for(a=0;
a<b;
a++){o(ue_err.erl[a]);
}};
r();
l.ueLogError=o;
})(window);
