(function(q){var f;
f={};
(function(){function L(R){return R<10?"0"+R:R;
}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(R){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+L(this.getUTCMonth()+1)+"-"+L(this.getUTCDate())+"T"+L(this.getUTCHours())+":"+L(this.getUTCMinutes())+":"+L(this.getUTCSeconds())+"Z":null;
};
String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(R){return this.valueOf();
};
}var K=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,N=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,O,J,Q={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},P;
function w(R){N.lastIndex=0;
return N.test(R)?'"'+R.replace(N,function(S){var T=Q[S];
return typeof T==="string"?T:"\\u"+("0000"+S.charCodeAt(0).toString(16)).slice(-4);
})+'"':'"'+R+'"';
}function M(Y,V){var T,S,Z,R,W=O,U,X=V[Y];
if(X&&typeof X==="object"&&typeof X.toJSON==="function"){X=X.toJSON(Y);
}if(typeof P==="function"){X=P.call(V,Y,X);
}switch(typeof X){case"string":return w(X);
case"number":return isFinite(X)?String(X):"null";
case"boolean":case"null":return String(X);
case"object":if(!X){return"null";
}O+=J;
U=[];
if(Object.prototype.toString.apply(X)==="[object Array]"){R=X.length;
for(T=0;
T<R;
T+=1){U[T]=M(T,X)||"null";
}Z=U.length===0?"[]":O?"[\n"+O+U.join(",\n"+O)+"\n"+W+"]":"["+U.join(",")+"]";
O=W;
return Z;
}if(P&&typeof P==="object"){R=P.length;
for(T=0;
T<R;
T+=1){if(typeof P[T]==="string"){S=P[T];
Z=M(S,X);
if(Z){U.push(w(S)+(O?": ":":")+Z);
}}}}else{for(S in X){if(Object.prototype.hasOwnProperty.call(X,S)){Z=M(S,X);
if(Z){U.push(w(S)+(O?": ":":")+Z);
}}}}Z=U.length===0?"{}":O?"{\n"+O+U.join(",\n"+O)+"\n"+W+"}":"{"+U.join(",")+"}";
O=W;
return Z;
}}if(typeof f.stringify!=="function"){f.stringify=function(U,S,T){var R;
O="";
J="";
if(typeof T==="number"){for(R=0;
R<T;
R+=1){J+=" ";
}}else{if(typeof T==="string"){J=T;
}}P=S;
if(S&&typeof S!=="function"&&(typeof S!=="object"||typeof S.length!=="number")){throw new Error("JSON.stringify");
}return M("",{"":U});
};
}}());
var C="1",z="//"+ue.furl+"/1/batch/"+C+"/OP/",i="/",t="$",u="&",e="=",d=",",G="_",y=":",g="%",j=2000,b=60000,s=5,k=1000,r,F,x=0,o=0,p={},v=function(w){return(""+w).length;
},E=(q.JSON&&q.JSON.stringify)||(f&&f.stringify),H=function(w){return(w&&w.r)||q.ue.rid;
},c=function(w){return(w&&w.s)||q.ue.sid;
},B=function(w){return(w&&w.m)||q.ue.mid;
},m=function(K,J,w){D(K,J,w,ue.d());
},D=function(ad,W,L,ab,Z){if(Z){L||(L={});
L.r||(L.r=Z);
}var R=H(L)+":"+W;
p[R]=(p[R]||0)+1;
if(p[R]>k){var V="ns '"+W+"' reached the max no of calls ("+k+") - aborting log of "+ad;
if(p[R]==(k+1)){m({m:V,f:"forester-client.js"},"jserr",L);
}return;
}var w=B(L)+y+c(L)+y+H(L),N=0,O,Q=""+ab,P=ad,ac,U,X,J,M="s",T=typeof ad,K=L&&L.n||false,S,Y,aa;
if(T=="undefined"){P="";
M="u";
}else{if(ad==null){P="";
M=null;
}else{if(T=="boolean"){P=ad?"1":"0";
M="b";
}else{if(T=="number"&&!isNaN(ad)&&isFinite(ad)){P=""+ad;
M="n";
}else{if(T=="object"){if(E){P=E(ad);
M="j";
}else{P=""+ad;
}}}}}}P=q.encodeURIComponent(P);
aa=j-v(w)-v(W)-v(Q)-2;
if(M!=null){aa-=(v(M)+2);
}while(P!=""){N++;
S=n(w,W,P,Q,M);
Y=j-r;
if(S<=Y){ac=P;
U="";
Y-=S;
r+=S;
}else{if(v(P)<=aa){l();
continue;
}else{X=Y-(S-v(P));
if(s<=X){X-=P.charAt(X-1)==g?1:P.charAt(X-2)==g?2:0;
ac=P.substr(0,X);
U=P.substr(X);
Y=0;
r=j;
O||(O=1+Math.ceil(v(U)/aa));
}else{if(j-(S-v(P))<s){return;
}l();
continue;
}}}F[w]||(F[w]=[]);
J=M!=null?M+y+ac+y+Q:Q;
if(O){J+=y+N+G+O;
}if(!F[w][W]){F[w][W]=J;
}else{F[w][W]+=d+J;
}if(Y==0||K){l();
}P=U;
}x++;
},h=function(){if(!ue.lr){return;
}var K=ue.lr.length,w,J;
for(J=0;
J<K;
J++){w=ue.lr[J];
D(w[1],w[2],w[3],w[4],w[5]);
}ue.lr=null;
},n=function(N,K,L,M,J){var w=v(M);
if(J!=null){w+=v(J)+v(L)+2;
}if(!F[N]){w+=v(N)+v(K)+2;
if(F.length>0){w++;
}}else{if(!F[N][K]){w+=v(K)+1;
if(F[N].length>0){w++;
}}else{w++;
}}return w;
},A=function(){r=0;
F=[];
},I=function(){if(r==0){return;
}var M="",K,L,J,w;
for(J in F){if(M!=""){M+=i;
}M+=J+t;
K=F[J];
L=true;
for(w in K){if(!L){M+=u;
}L=false;
M+=w+e+K[w];
}}q.ue.w=M;
new Image().src=z+M;
o++;
A();
},l=I,a=q.onbeforeunload;
q.onbeforeunload=function(w){if(a){a(w);
}l();
};
q.setInterval(function(){l();
},b);
A();
h();
q.ue.log=m;
q.amznJQ.declareAvailable("forester-client");
})(window);
